bind = "127.0.0.1"
port = 8080
mysql_server = "127.0.0.1"
mysql_port = 3306
mysql_user = "admin"
mysql_password = "password"
mysql_database = "recreationroom"
mysql_options = "charset=utf8mb4&parseTime=true"
debug = true
