[session]
backend = "redis"

[session.redis]
server = "127.0.0.1"
port = 6379
password = ""
db = 0

[database]
backend = "mysql"

[database.mysql]
server = "localhost"
port = 3306
user = "admin"
password = "password"
database = "recreationroom"
options = "charset=utf8mb4"
